version: "3"
services:
  mjbot:
    build: .
    image: mjmjelde/mjdiscord
    restart: unless-stopped
    volumes:
      - "mjbotdada:/opt/mjdiscord/data"
      - "./config:/opt/mjdiscord/config"
      - "./audio:/opt/mjdiscord/audio"
volumes: 
  mjbotdada: